_target_: evaluators.kuka_pusher_long_context_evaluator.KukaPlanarPusherLongContextBlockEvaluator

min_seed: 2000 
max_seed: 2001

checkpoint_directory: "/home/abhinav/RLG/gcs-diffusion/data/outputs/long_context_planar_pushing/two_modes/unet_cross_attention/constant_obs_steps_0_mirror/30_obs/checkpoints"

num_processes: 4 
save_html_first: 20 
eval_max_time: 50.0