_target_: controllers.ee_diffusion_planar_controller.PlanarDiffusionPolicyDrakeController

checkpoint_path: "/home/abhinav/RLG/gcs-diffusion/data/outputs/test_lc_task/10_obs/checkpoints/latest.ckpt"
relative_path_to_diffusion_model: "../../RLG/gcs-diffusion"

load_normalizer_from_file: true 
infer_frozen_policy: true 
use_DDIM: true 

policy_device: "cuda"

initial_planar_command: [0.3, 0.0, 0.175] # this is only used at start, after which reset takes over 

eval_min_seed: 1000
eval_max_seed: 1010 

eval_max_time: 30.0 

controller_dt: 0.1