_target_: controllers.ee_diffusion_planar_controller.PlanarDiffusionPolicyDrakeController

# checkpoint_path: "/home/abhinav/RLG/gcs-diffusion/data/outputs/long_planar_pushing_basic/new_architecture/constant_obs_steps/5_obs/checkpoints/latest.ckpt"
checkpoint_path: "/home/abhinav/RLG/gcs-diffusion/data/outputs/long_context_planar_pushing/two_modes/unet_cross_attention/constant_obs_steps/5_obs/checkpoints/latest.ckpt"
# checkpoint_path: "/home/abhinav/RLG/gcs-diffusion/data/outputs/long_context_planar_pushing/two_modes/unet_cross_attention/constant_obs_steps/48_obs/checkpoints/epoch=0216-val_loss=0.0168-val_ddim_mse=0.0001.ckpt"

# checkpoint_path: "/home/abhinav/RLG/gcs-diffusion/data/outputs/long_context_planar_pushing/two_modes/unet_film/5_obs/checkpoints/latest.ckpt"
# checkpoint_path: "/home/abhinav/RLG/gcs-diffusion/data/outputs/long_context_planar_pushing/two_modes/unet_cross_attention/constant_obs_steps/5_obs/checkpoints/epoch=0126-val_loss=0.0236-val_ddim_mse=0.0004.ckpt"

relative_path_to_diffusion_model: "../../RLG/gcs-diffusion"

load_normalizer_from_file: true 
infer_frozen_policy: true 
use_DDIM: true 

policy_device: "cuda"

initial_planar_command: [0.3, 0.0, 0.175] # this is only used at start, after which reset takes over 

eval_min_seed: 2000
eval_max_seed: 2050 

eval_max_time: 50.0

controller_dt: 0.1

n_action_steps_override: 8

modes_to_eval: [0, 4]

visualize_actions: true 

save_html_first: 20 
save_trajectory: true 

num_samples: 1